### ISSUE TITLE
[gstreamer-vaapi][vpp] CSC fail.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#155]
System Environment
OS Ubuntu 17.04
Kernel 4.10
Hardware Skylake Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
libva tag 2.1.0
intel-media-driver f6283e2
gst-vaapi tag 1.13.90

Reproduce Steps
Use gst cmd to convert NV12 to I420/YUY2/RGBX , and then render picture, but I420 format display black, YUY2/RGBX cmdline fail.
$ gst-launch-1.0 videotestsrc ! vaapipostproc format=2 ! vaapisink
$ gst-launch-1.0 videotestsrc ! vaapipostproc format=4 ! vaapisink
$ gst-launch-1.0 videotestsrc ! vaapipostproc format=7 ! vaapisink

Only YV12 looks good:
$ gst-launch-1.0 videotestsrc ! vaapipostproc format=3 ! vaapisink

**Comment by FurongZhang** [comment]
We are working in progress to reproduce it.

**Comment by FurongZhang** [comment]
NV12->I420 is related to VP, we will fix it. But for NV12->YUY2 and NV12->RGBX, no VP function is called.

**Comment by FurongZhang** [comment]
@feiwan1 Is it possible for you to take a look at NV12->YUY2 and NV12->RGBX?

**Comment by feiwan1** [comment]
@FurongZhang , Is all csc should go through VP function in driver? Is there any other way to do csc?

**Comment by FurongZhang** [comment]
CSC should go through VP function in driver.

**Comment by FurongZhang** [comment]
@feiwan1  This issue is fixed. Please use the latest driver(ww36) to verify that. The fix, please refer to the function in DdiMedia_CreateImage. We will close this if you verify it, thanks a lot in advance!

**Comment by feiwan1** [comment]
@wangzj0601, Could you help to verify this patch? Thanks.

**Comment by FurongZhang** [comment]
@wangzj0601, is it possible for you to verify it? Thanks a lot in advance!

**Comment by FurongZhang** [comment]
Pending on submitter to verify that.

**Comment by wangzj0601** [comment]
it can be pass when convert to I420, YV12 or YUY2,  but still fail when convert NV12 to RGBX with driver version ba63dbe

**Comment by feiwan1** [comment]
By using glimagesink instead of vaapisink, all case looks good. So close this issue.

Thanks @FurongZhang for fixing this.
